apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: www.mylearncloud.shop
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-green
                port:
                  number: 80
    - host: keycloak.mylearncloud.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak  # fully qualified service name
                port:
                  number: 8080

    - host: grafana.mylearncloud.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana  # fully qualified service name
                port:
                  number: 80

  tls:
    - hosts:
        - www.mylearncloud.shop
      secretName: mylearncloud-tls
    - hosts:
        - keycloak.mylearncloud.shop
      secretName: keycloak-tls  # create or reuse a TLS secret for Keycloak
    - hosts:
        - grafana.mylearncloud.shop
      secretName: grafana-tls